### PR TITLE
UI fix for drops outside of case logic

### PR DESCRIPTION
**Pull request by barneycarroll**
If you drag a piece onto an illegal square or off the table, no other pieces can be moved unless the badly dropped piece is legally dropped.

This adds an extra fallback clause if no legal move conditions are met on drop with the same result as 'same square'.

### CODE REVIEW

**Comment by glinscott** [comment]
Thanks for the bug report, and the pull request!  The commit seems to be empty though?

**Comment by barneycarroll** [comment]
Oops, sorry. The pertinent change is here: 9c8e7af67086f906a1af5ab214d5f7b13c9adba4

**Comment by glinscott** [comment]
Ah, great, thanks.  Maybe merge the move == null check with the "if (startX == endX && startY == endY)" check just a little earlier?

**Comment by glinscott** [comment]
Thanks!  Merged.

**Pull request merged**
